title: "Songzi Vuong's Blog"
author: Songzi Vuong
email: songzivuong@gmail.com
description: "Wrting is thinking."

show_excerpts: true

minima:
  date_format: "%b %-d, %Y"
  social_links:
    twitter: SongziVuong
    github:  songzivuong
    rss: rss

header_pages:
  - about.md

remote_theme: jekyll/minima

plugins:
  - jekyll-seo-tag
  - jekyll-feed
