title: "Songzi Vuong's Blog"
author: Songzi Vuong
email: songzivuong@gmail.com
description: "Writing is thinking."

permalink: /:year/:month/:day/:title.html

show_excerpts: true

minimax:
  date_format: "%b %-d, %Y"
  posts_limit: 20
  social_links:
    twitter: SongziVuong
    github:  songzivuong
    rss: rss

header_pages:
  - about.md
  - tags.md

remote_theme: songzivuong/jekyll-theme-minimax

plugins:
  - jekyll-seo-tag
  - jekyll-feed

disqus:
  shortname: songzivuong

google_analytics: UA-134434672-1

markdown: kramdown
kramdown:
  parse_block_html: true