title: "Songzi Vuong's Blog"
author: Songzi Vuong
email: songzivuong@gmail.com
description: "Wrting is thinking."

show_excerpts: true

minimax:
  date_format: "%b %-d, %Y"
  social_links:
    twitter: SongziVuong
    github:  songzivuong
    rss: rss

header_pages:
  - about.md

#theme: minimax
remote_theme: songzivuong/minimax

plugins:
  - jekyll-seo-tag
  - jekyll-feed

disqus:
  shortname: songzivuong

google_analytics: UA-134434672-1